version: 2.1

jobs:
  build:
    script:
      - echo "Hello, World!"

      # Install Docker in the image
      - apt-get update -qy
      - apt-get install -y docker.io

      # Build Docker image
      - docker build -t charanl/my-python-app:latest .

      # Run tests
      - pip install -r requirements.txt
      - pytest -v test_sparse_recommender.py
