version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
      - image: mysql:8.0.33
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      
      - run:
          name: Run tests
          command: |
             pytest -v test_sparse_recommender.py
      - run:
          name: Debug Info
          command: |
              pwd
              ls -R
              pytest -v test_sparse_recommender.py
